project:
  type: website

website:
  title: "Metagenomics bioinformatics at MGnify (2023)"
  favicon: static/mgnify_logo.png
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - href: https://www.ebi.ac.uk/metagenomics
        text: Open MGnify
      - href: https://www.ebi.ac.uk/training/events/metagenomics-bioinformatics-1/#vf-tabs__section--tab2
        text: Course Programme

  sidebar:
    style: docked
    search: true

    contents: auto

  reader-mode: true

format:
  html:
    theme: 
      - cosmo
      - styles.scss
    toc: true



